env:
  node: true
  es6: true
  mocha: true

parserOptions:
  ecmaVersion: 2020

plugins:
  - haraka

extends:
  - eslint:recommended
  - plugin:haraka/recommended

root: true

rules:
  indent: [2, 2, { SwitchCase: 1 } ]