name: CI

on:
  push:

env:
  CI: true

jobs:
  lint:
    uses: haraka/.github/.github/workflows/lint.yml@master

  coverage:
    uses: haraka/.github/.github/workflows/coverage.yml@master
    secrets: inherit

  get-lts:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - id: get-tls
        uses: msimerson/node-lts-versions@v1.2.2
    outputs:
      lts: ${{ steps.get-tls.outputs.lts }}
      active: ${{ steps.get-tls.outputs.active }}

  test:
    needs: get-lts
    runs-on: ${{ matrix.os }}
    # services:
    #   redis:
    #     image: redis
    #     ports:
    #       - 6379:6379
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        node-version: ${{ fromJson(needs.get-lts.outputs.active) }}
      fail-fast: false

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      name: Node ${{ matrix.node-version }} on ${{ matrix.os }}
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm install

    - run: npm test
